# Generated by Django 5.0.6 on 2024-07-15 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datos_abuelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('edad', models.IntegerField(default=65, validators=[django.core.validators.MaxValueValidator(110)])),
                ('fecha_inicio_cont', models.DateField()),
                ('fecha_paga', models.DateField()),
                ('monto_pagado', models.IntegerField()),
                ('cant_pag_atrasados', models.IntegerField()),
                ('monto_atrasado', models.IntegerField()),
            ],
        ),
    ]
